### ISSUE TITLE
GitSync corrupting code blocks in issues

### ISSUE THREAD

**Issue by krowlandson** [a11smiles/GitSync#3]
@a11smiles ... we have noticed that each time GitSync runs against an issue, it appears to modify the original issue.

With the fact that GitSync performs all actions under a PAT token this makes it look like the owner of the PAT has made changes:

![image](https://user-images.githubusercontent.com/12268562/192254589-6fcd1eec-a404-4022-90d5-188388cf851e.png)

This would seem harmless (_although I don't believe this should be necessary_) except we have noticed that these changes are actually causing code snippets provided in the request and other formatting to become corrupted.

For example, see the following code snippet which was originally valid HCL:

![image](https://user-images.githubusercontent.com/12268562/192254945-708283b8-ae28-48da-812c-a51ef8fb5405.png)

And how it resulted in the following code being re-written into the issue:

![image](https://user-images.githubusercontent.com/12268562/192255052-cfffc850-81c9-432f-be5c-ba8c7dcf8808.png)

**Comment by jtracey93** [comment]
This is happening in all the other ALZ repos

**Comment by jtracey93** [comment]
Sorry to chase @a11smiles but this is really hurting us now and slowing us down triaging etc.

Any ETA on a fix or investigation?

Thanks in advance

cc: @mblant @krowlandson
